export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_SEARCH_PRODUCTS = "GET_SEARCH_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const USER_LOGIN = "USER_LOGIN";
export const GET_USERINFO = "GET_USERINFO";
export const GET_CART = "GET_CART";
export const GET_CHECKOUT = "GET_CHECKOUT";
export const GET_ORDERDETAIL = "GET_ORDERDETAIL";
export const GET_CATEGORIES = "GET_CATEGORIES";

